Farm.WebSite/Controllers/Admin/AdminRauSachController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Entity;
using Farm.Repository.IService;
using Farm.WebSite.ViewModel;

namespace Farm.WebSite.Controllers.Admin
{
    public class AdminRauSachController : Controller
    {
        private ICategoryService _iCategoryService;
        private IEventServices _iEventService;
        private IProductService _iProductService;

        public AdminRauSachController(ICategoryService iCategoryService, IEventServices iEventService, IProductService iProductService)
        {
            _iCategoryService = iCategoryService;
            _iEventService = iEventService;
            _iProductService = iProductService;
        }
        // GET: AdminRauSach
        public ActionResult Index()
        {

            return View();
        }
        #region Categories
        public ActionResult Categories()
        {
            var result = _iCategoryService.GetAll();
            return View(result.ToList());
        }

        public ActionResult GetCategories()
        {
            try
            {
                var result = _iCategoryService.GetAll();
                return View(result.ToList());
            }
            catch (System.Exception ex)
            {
                return Json(ex);
            }

        }

        public ActionResult DeleteCategory(int id)
        {
            _iCategoryService.Delete(id);
            return Json(new { data = "success", message = "Xóa sản phẩm thành công" });
        }

        public ActionResult EditCategory(int pk, string name, string value)
        {
            _iCategoryService.Edit(pk, name, value);
            return Json(new { data = "success", message = "Xóa sản phẩm thành công" });
        }


        public ActionResult AddCategory()
        {
            return View("_AddCategories");
        }


        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            _iCategoryService.Add(category);
            return Json(new
            {
                data = "success",
                message = "Thêm Thành Công"
            }, JsonRequestBehavior.AllowGet);
            /*    return Json(new { data = "success", message = "Thêm Thành Công" });*/
        }
        #endregion
        #region Event

        public ActionResult Events()
        {
            return View();
        }

        public ActionResult GetEvent()
        {
            var result = _iEventService.GetAll();
            return View(result.ToList());
        }

        public ActionResult AddEvent()
        {
            return PartialView("_AddCEvents");
        }

        [HttpPost]
        public ActionResult AddEvent(EventViewModel eventViewModel, List<HttpPostedFileBase> images)
        {
            FarmContext db = new FarmContext();
            var @event = new Event()
            {
                Label = eventViewModel.Label,
                Description = eventViewModel.Description,
                Content = eventViewModel.Content,
                CreateDate = DateTime.Now
            };
            _iEventService.Add(@event);
            //todo:Refactor to service Add Image and design agian for table image (Too many Id and missing ext(.png.jpg),Name)
            try
            {
                foreach (HttpPostedFileBase item in eventViewModel.files)
                {
                    var fileData = new MemoryStream();
                    item.InputStream.CopyTo(fileData);

                    var imageEvent = new ImageContain()
                    {
                        EventId = @event.Id,
                        CreateDate = DateTime.Now,
                        Image = fileData.ToArray(),
                    };
                    db.ImageContains.Add(imageEvent);
                    db.SaveChanges();
                }
                return Json(new { data = "success", message = "Thêm Thành Công" });
            }
            catch (Exception)
            {
                return Json(new { data = "error", message = "Hình lớn hơn 2MB" });
            }

        }

        public ActionResult EditEvent(int pk, string name, string value)
        {
            _iEventService.Edit(pk, name, value);
            return Json(new { data = "success", message = "Sửa sản phẩm thành công" });
        }

        public ActionResult DeleteEvent(int id)
        {
            _iEventService.Delete(id);
            return Json(new { data = "success", message = "Xóa sản phẩm thành công" });
        }
        #endregion
        #region Product

        public ActionResult Product()
        {
            return View();
        }

        public ActionResult GetProduct()
        {
            try
            {
                var result = _iProductService.GetAll();
                return View(result.ToList());
            }
            catch (System.Exception ex)
            {
                return Json(ex);
            }
        }

        public ActionResult AddProduct()
        {
            var category = _iCategoryService.GetAll();
            var productViewModel = new ProductViewModel();
            productViewModel.Category = category.ToList().Select(f => new SelectListItem()
            {
                Text = f.Label,
                Value = f.Id.ToString()
            }).ToList();
            return PartialView("_AddProduct", productViewModel);
        }

        [HttpPost]
        public ActionResult AddProduct(ProductViewModel productViewModel, HttpPostedFileBase files)
        {
            FarmContext db = new FarmContext();
            var product = new Product()
            {
                Description = productViewModel.Description,
                CreateDate = DateTime.Now,
                CategoryId = productViewModel.CategoryId,
                Name = productViewModel.Name,
                Price = productViewModel.Price,
                Quatity = productViewModel.Quatity,
            };
            _iProductService.Add(product);

            //todo:Refactor to service Add Image and design agian for table image (Too many Id and missing ext(.png.jpg),Name)
            try
            {
                foreach (HttpPostedFileBase item in productViewModel.files)
                {
                    var fileData = new MemoryStream();
                    item.InputStream.CopyTo(fileData);

                    var imageEvent = new ImageContain()
                    {
                        ProductId = product.Id,
                        CreateDate = DateTime.Now,
                        Image = fileData.ToArray(),
                    };
                    db.ImageContains.Add(imageEvent);
                    db.SaveChanges();
                }
                return Json(new { data = "success", message = "Thêm Thành Công" });
            }
            catch (Exception)
            {
                return Json(new { data = "error", message = "Hình lớn hơn 2MB" });
            }
        }

        public ActionResult EditProduct(int pk, string name, string value)
        {
            _iProductService.Edit(pk, name, value);
            return Json(new { data = "success", message = "Sửa sản phẩm thành công" });
        }

        public ActionResult DeleteProduct(int id)
        {
            _iProductService.Delete(id);
            return Json(new { data = "success", message = "Xóa Thành Công" });
        }

        public ActionResult ProductDetail(int id)
        {
            _iProductService.GetById(id);
            return View();
        }
        #endregion
    }
}

Farm.WebSite/Views/AdminRauSach/Categories.cshtml
@model IList<Domain.Entity.Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link rel="stylesheet" type="text/css"
      href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<h2>Index</h2>
<div id="divCategory" data-autoload="@Url.Action("GetCategories","AdminRauSach")">
    
</div>
<div class="panel-footer">
    <div class="row">
        <div class="col-sm-8">
            <button type="button" class="btn-success btn" id="openDialog" data-url="@Url.Action("AddCategory", "AdminRauSach")">Thêm loại rau</button>
        </div>
    </div>
</div>
<div id="dialog-edit">
</div>
<div id="dialog-view" style="display: none">
</div>  
<script>
    $(document).ready(function () {
        Autoload($('#divCategory'));
    });

    function Autoload(target) {
        var url = target.data('autoload');
        target.load(url);
    }
    $(document).on("click","#openDialog", function (e) {
        debugger;
        e.preventDefault();
        var url = $(this).data('url');

        $("#dialog-edit").dialog({

            autoOpen: false,
            resizable: false,
            height: 455,
            width: 500,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar").hide();
                $(this).load(url);
            },
            close: function (event, ui) {
                $(this).dialog('close');
            }
        });

        $("#dialog-edit").dialog('open');
        return false;
    });

    $(document).on("click", '.closeCategory', function() {
        close_dialog();
    });

    $(document).on("click", '.close', function () {
        close_dialog();
    });
    function close_dialog() {
        //Close jQuery UI dialog 
        $("#dialog-edit").dialog('close');
        $('#form').die('click');
    }
</script>

Farm.WebSite/Views/AdminRauSach/Events.cshtml
@{
    ViewBag.Title = "Events";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link rel="stylesheet" type="text/css"
      href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<h2>Events</h2>

<div id="divEvent" data-autoload="@Url.Action("GetEvent","AdminRauSach")">

</div>
<div class="panel-footer">
    <div class="row">
        <div class="col-sm-8">
            <button type="button" class="btn-success btn" id="openDialog" data-url="@Url.Action("AddEvent", "AdminRauSach")">Thêm sự kiện</button>
        </div>
    </div>
</div>
<div id="dialog-edit">
</div>
<div id="dialog-view" style="display: none">
</div>  

<script>
    $(document).ready(function () {
        Autoload($('#divEvent'));
    });

 
    $(document).on("click","#openDialog", function (e) {
        debugger;
        e.preventDefault();
        var url = $(this).data('url');

        $("#dialog-edit").dialog({

            autoOpen: false,
            resizable: false,
            height: 800,
            width: 700,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar").hide();
                $(this).load(url);
            },
            close: function (event, ui) {
                $(this).dialog('close');
            }
        });

        $("#dialog-edit").dialog('open');
        return false;
    });

    $(document).on("click", '.closeCategory', function() {
        close_dialog();
    });
</script>

Farm.WebSite/Views/AdminRauSach/GetCategories.cshtml
@model IList<Domain.Entity.Category>

@{
    ViewBag.Title = "Index";
    Layout = null;
}
<link href="~/Content/bootstrap-editable.css" rel="stylesheet" />
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

<script src="~/Scripts/bootstrap-editable.js"></script>

<div class="row">
    <table class="table table-striped">
        <thead>
            <tr class="warning">
                <th>Number</th>
                <th>Label</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>
                        <a class="label-category" href="#" id="username12" data-type="text" data-pk="@item.Id" data-url='@Url.Action("EditCategory", "AdminRauSach")' 
                           data-title="Sửa tên loại rau">@item.Label</a></td>
                    <td>@item.Description</td>
                    <td><i class="fa fa-trash-o fa-lg deleteCategory" value="@item.Id" id="deleteCategory-@item.Id" name="@item.Id"></i></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        debugger;
        $('.label-category').editable({
            name:  'Label',
            type: 'text',
            url: '@Url.Action("EditCategory", "AdminRauSach")',
            title: 'Enter Label'
        });
    });

   
    $('.deleteCategory').click(function () {
        debugger;
        var categoryId = $(this).attr("name");
        var a = 1;
        var url = '@Url.Action("DeleteCategory", "AdminRauSach")';
        $.ajax({
            type: "POST",
            url: url,                           // Any URL
            data: {"id" : categoryId},                 // Serialize the form data
            success: function (data) {                        // If 200 OK
                ShowSuccess(data.message);
                Autoload($('#divCategory'));
            },
            error: function (xhr, text, error) {              // If 40x or 50x; errors
                alert('Error: ' + error);
            }
        });
    });
</script>

Farm.WebSite/Views/AdminRauSach/GetEvent.cshtml
@model IList<Domain.Entity.Event>

@{
    ViewBag.Title = "Index";
    Layout = null;
}
<link href="~/Content/bootstrap-editable.css" rel="stylesheet" />
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Content/jquery.fileupload.css" rel="stylesheet" />
<link href="~/Content/jquery.fileupload-noscript.css" rel="stylesheet" />
<link href="~/Content/jquery.fileupload-ui-noscript.css" rel="stylesheet" />
<link href="~/Content/jquery.fileupload-ui.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-editable.js"></script>
<script src="~/scripts/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
        // Initialize your tinyMCE Editor with your preferred options
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "modern",
            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|, styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|, link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|, forecolor,backcolor,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|, styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|, visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Example content CSS (should be your site CSS)
            content_css: "css/example.css",
        });
</script>
<div class="row">
    <table class="table table-striped">
        <thead>
        <tr class="warning">
            <th>Number</th>
            <th>Label</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>
                    <a class="label-category" href="#" id="username12" data-type="text" data-pk="@item.Id" data-url='@Url.Action("EditEvent", "AdminRauSach")'
                       data-title="Sửa tên sự kiện">@item.Label</a>
                </td>
                <td> @Html.Raw(item.Description)</td>
                <td>
                    <i class="fa fa-trash-o fa-lg deleteCategory" value="@item.Id" id="deleteCategory-@item.Id" name="@item.Id"></i>
                    
                    <a href="/Home/HomeEvent?eventId=@item.Id" class="button hvr-wobble-bottom"><span class="fa fa-info"> </span></a>
                </td>

            </tr>
        }
        </tbody>
    </table>
</div>

<script>

    $(document).ready(function () {
        debugger;
        $('.label-category').editable({
            name:  'Label',
            type: 'text',
            url: '@Url.Action("EditEvent", "AdminRauSach")',
            title: 'Enter Label'
        });
    });

    $('.deleteCategory').click(function () {
        debugger;
        var categoryId = $(this).attr("name");
        var a = 1;
        var url = '@Url.Action("DeleteEvent", "AdminRauSach")';
        $.ajax({
            type: "POST",
            url: url,                           // Any URL
            data: {"id" : categoryId},                 // Serialize the form data
            success: function (data) {                        // If 200 OK
                ShowSuccess(data.message, "success", 3000);
                Autoload($('#divEvent'));
            },
            error: function (xhr, text, error) {
                debugger;// If 40x or 50x; errors
                showErrors('Error: ' + error);
            }
        });
    });
</script>

Farm.WebSite/Views/AdminRauSach/GetProduct.cshtml
@using Domain.Entity
@model IList<Domain.Entity.Product>

@{
    ViewBag.Title = "Index";
    Layout = null;
}
<link href="~/Content/bootstrap-editable.css" rel="stylesheet" />
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<script src="~/Scripts/bootstrap-editable.js"></script>

<div class="row">
    <table class="table table-striped">
        <thead>
            <tr class="warning">
                <th style="text-align:center; vertical-align:middle">Image</th>
                <th style="text-align:center; vertical-align:middle">Name</th>
                <th style="text-align:center; vertical-align:middle">Price</th>
                <th style="text-align:center; vertical-align:middle">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:250px; height:250px; text-align:center; vertical-align:middle">
                    @if (item.ImageContains != null)
                    {
                        var firstOrDefault = item.ImageContains.ToList().FirstOrDefault();
                        if (firstOrDefault != null)
                        {
                            var base64 = Convert.ToBase64String(firstOrDefault.Image);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            @:<img src="@imgSrc" class="img-responsive" alt="" />
                        }
                    }</td>
                    <td style="text-align:center; vertical-align:middle">
                        <a class="label-name" href="#" data-type="text" data-pk="@item.Id" data-url='@Url.Action("EditProduct", "AdminRauSach")'
                           data-title="Sửa tên loại rau">@item.Name</a>
                    </td>
                    <td style="text-align:center; vertical-align:middle">
                        <a class="label-price" href="#" data-type="text" data-pk="@item.Id" data-url='@Url.Action("EditProduct", "AdminRauSach")'
                           data-title="Sửa Giá Tiền">@item.Price</a>
                    </td>
                    <td style="text-align:center; vertical-align:middle"><i class="fa fa-trash-o fa-lg deleteCategory" value="@item.Id" id="deleteCategory-@item.Id" name="@item.Id"></i></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        $('.label-name').editable({
            name: 'Name',
            type: 'text',
            url: '@Url.Action("EditProduct", "AdminRauSach")',
            title: 'Enter Name',
            success: function (response, newValue) {
                ShowSuccess("Sửa Thành Công");
            }
        });

        $('.label-price').editable({
            name: 'Price',
            type: 'text',
            url: '@Url.Action("EditProduct", "AdminRauSach")',
            title: 'Enter Price',
            success: function (response, newValue) {
                ShowSuccess("Sửa Thành Công");
            }
        });
    });


    $('.deleteCategory').click(function () {
        debugger;
        var productId = $(this).attr("name");
        var url = '@Url.Action("DeleteProduct", "AdminRauSach")';
        $.ajax({
            type: "POST",
            url: url,                           // Any URL
            data: { "id": productId },                 // Serialize the form data
            success: function (data) {                        // If 200 OK
                ShowSuccess(data.message);
                Autoload($('#divProduct'));
            },
            error: function (xhr, text, error) {              // If 40x or 50x; errors
                showErrors('Error: ' + error);
            }
        });
    });
</script>

Farm.WebSite/Views/AdminRauSach/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

Farm.WebSite/Views/AdminRauSach/Product.cshtml
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link rel="stylesheet" type="text/css"
      href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<h2>Product</h2>
<div id="divProduct" data-autoload="@Url.Action("GetProduct","AdminRauSach")">

</div>
<div class="panel-footer">
    <div class="row">
        <div class="col-sm-8">
            <button type="button" class="btn-success btn" id="openDialog" data-url="@Url.Action("AddProduct", "AdminRauSach")">Thêm Sản Phẩm</button>
        </div>
    </div>
</div>
<div id="dialog-edit">
</div>
<div id="dialog-view" style="display: none">
</div>

<script>
    $(document).ready(function () {
        Autoload($('#divProduct'));
    });

    function Autoload(target) {
        var url = target.data('autoload');
        target.load(url);
    }
    $(document).on("click","#openDialog", function (e) {
        debugger;
        e.preventDefault();
        var url = $(this).data('url');
        $("#dialog-edit").dialog({
            autoOpen: false,
            resizable: false,
            height: 600,
            width: 500,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar").hide();
                $(this).load(url);
            },
            close: function (event, ui) {
                $(this).dialog('close');
            }
        });

        $("#dialog-edit").dialog('open');
        return false;
    });

    $(document).on("click", '.closeProduct', function() {
        close_dialog();
    });

    $(document).on("click", '.close', function () {
        close_dialog();
    });
</script>  

Farm.WebSite/Views/AdminRauSach/Test.cshtml
@model IEnumerable<Domain.Entity.ImageContain>

@using (Html.BeginForm("Test", "AdminRauSach", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()

    foreach (var item in Model)
    {
        if (item.Image != null)
        {
            var base64 = Convert.ToBase64String(item.Image);
            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            <img src="@imgSrc" style="max-height:250px" />
        }
    }
    <div class="form-field">
        <input type="file" name="images" multiple="multiple" />
        <input type="file" name="image2" />
        <input type="file" name="image3" />
    </div>

            <div class="form-field">
                <input type="submit" value="Create" />
            </div>
}

Farm.WebSite/Views/AdminRauSach/_AddCEvents.cshtml
@model Farm.WebSite.ViewModel.EventViewModel
<script src="~/scripts/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
        // Initialize your tinyMCE Editor with your preferred options
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "modern",
            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|, styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|, link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|, forecolor,backcolor,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|, styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|, visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Example content CSS (should be your site CSS)
            content_css: "css/example.css",
        });
</script>
    @using (Html.BeginForm("AddEvent", "AdminRauSach", FormMethod.Post, new { @id = "AddEvent" }))
    {
        <div class="modal-header">
            <h4 class="modal-title">Thêm Sự Kiện</h4>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label for="Label">Tên</label>
                @Html.TextBoxFor(m => m.Label, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label for="Label">Mô Tả</label>
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="Description">Nội Dung</label>
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @rows = "5" })
            </div>

        </div>
        @Html.TextBoxFor(m => m.files,new { @type = "file", @multiple = "multiple"})
        <div class="modal-footer">
            <button type="button" class="btn btn-default closeCategory" data-dismiss="modal ">Đóng</button>
            <button type="button" class="btn btn-primary btnAddCategory">Lưu</button>
        </div>
    }
<script src="~/Scripts/jquery.fileupload.js"></script>
    <script>
        $('.btnAddCategory').off('click').on("click", function () {
            var formData = new FormData();
            var urlf = $('#AddEvent').attr('action');
            var totalFiles = document.getElementById("files").files.length;
            var label =$('#Label').val();
            var description = $('#Description').val();
            for (var i = 0; i < totalFiles; i++) {
                var file = document.getElementById("files").files[i];
                formData.append("files", file);
            }
            var content = tinyMCE.get('Content');
            var descriptionData = content.getContent();
            formData.append("Label", label);
            formData.append("Description", description);
            formData.append("Content", descriptionData);
            
            $.ajax({
                type: "POST",
                url: urlf,
                dataType: 'json',
                processData: false,
                contentType: false,
                data: formData,                 // Serialize the form data
                success: function (data) {                        // If 200 OK
                    ShowSuccess(data.message);
                    close_dialog();
                    Autoload($('#divEvent'));
                },
                error: function (xhr, text, error) {
                    alert("Hình lớn hơn 2mb");
                }
            });
        });

        $('#form').submit(function () {
            event.preventDefault();
            //......
        });

        function ValidateCategories() {
            
        }
    </script>

Farm.WebSite/Views/AdminRauSach/_AddProduct.cshtml
@model Farm.WebSite.ViewModel.ProductViewModel

@using (Html.BeginForm("AddProduct", "AdminRauSach", FormMethod.Post, new { @id = "AddProduct" }))
{
    <div class="modal-header">
        <h4 class="modal-title">Thêm Sản Phẩm</h4>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label for="Label">Tên</label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>

        @*        <div class="form-group">
                <label for="Label">Tên</label>
                @Html.TextBoxFor(m => m., new { @class = "form-control" })
            </div>*@

        <div class="form-group">
            <label for="Label">Giá</label>
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label for="Label">Mô Tả</label>
            @Html.TextBoxFor(m => m.Quatity, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label for="Description">Loại</label>
            @Html.DropDownListFor(model => model.Category, Model.Category, new { @class = "form-control", @rows = "5" })
        </div>

    </div>
        @Html.TextBoxFor(m => m.files, new { @type = "file", @multiple = "multiple" })
        <div class="modal-footer">
            <button type="button" class="btn btn-default closeProduct" data-dismiss="modal ">Đóng</button>
            <button type="button" class="btn btn-primary btnAddProduct">Lưu</button>
        </div>
}
<script src="~/Scripts/jquery.fileupload.js"></script>
<script>
    $('.btnAddProduct').off('click').on("click", function () {
        debugger;
        var formData = new FormData();
        var urlf = $('#AddProduct').attr('action');
        var totalFiles = document.getElementById("files").files.length;
        var name = $('#Name').val();
        var price = $('#Price').val();
        var quatiy = $('#Quatity').val();
        var category = $('#Category').val();
        for (var i = 0; i < totalFiles; i++) {
            var file = document.getElementById("files").files[i];
            formData.append("files", file);
        }

        formData.append("Name", name);
        formData.append("Price", price);
        formData.append("Quatity", quatiy);
        formData.append("CategoryId", category);

        $.ajax({
            type: "POST",
            url: urlf,
            dataType: 'json',
            processData: false,
            contentType: false,
            data: formData,                 // Serialize the form data
            success: function (data) {                        // If 200 OK
                ShowSuccess(data.message);
                close_dialog();
                Autoload($('#divProduct'));
            },
            error: function (xhr, text, error) {
                debugger;// If 40x or 50x; errors
                alert("Hình lớn hơn 2mb");
            }
        });
    });

    $('#form').submit(function () {
        event.preventDefault();
        //......
    });
</script>